### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by macfeaster** [datasektionen/gloo#1]
**Great job, this is gonna be awesome!**

I think there is room for some improvement in [`fileExistsPath`](https://github.com/JSimo/gloo/blob/master/find-template.js#L29):

We know from the configuration JSON whatever template engine a particular site is using. It should be possible to pass this down so we don't have to look for templates of all formats.

**Comment by LudwikJaniuk** [comment]
Currently, we do not know what template engine a file is using (at least it's not in the taitan data, and not in any config file in gloo). So this is rather an issue for taitan to send the data, but then, sure.

**Comment by macfeaster** [comment]
This should be stored on a per-site basis in a config file in gloo :)

**Comment by LudwikJaniuk** [comment]
Oh, in that case, we can add it.

**Comment by LudwikJaniuk** [comment]
We're going with subdomain, and this is implemented in the latest push.
