### ISSUE TITLE
Template resolving behavior differs

### ISSUE THREAD

**Issue by macfeaster** [datasektionen/gloo#4]
When accessing the root path `/` of any site, `domain.ext` is used instead of `domain/_default.ext`. On the other hand when accessing the path `/:slug`, the resolving acts the other way around. The `domain.ext` template should not be used, all templates should be kept in their folders.

**Comment by LudwikJaniuk** [comment]
Sounds reasonable, will change this.

**Comment by LudwikJaniuk** [comment]
Oh, github didn't notice me closing this. Oh well.

**Comment by macfeaster** [comment]
```
gloo:routes Subdomain is www +18s
gloo:find-template PATHL: /gloo/templates/www/namnder +0ms
gloo:find-template SITE: www/namnder +0ms
gloo:find-template trying /gloo/templates/www/namnder.jade[object Object] +0ms
gloo:find-template trying /gloo/templates/www/namnder.handlebars[object Object] +0ms
gloo:find-template trying /www/namnder.nunj[object Object] +0ms
gloo:find-template Could not find file /gloo/templates/www/namnder +0ms
gloo:find-template Found template file: undefined +0ms
```

Expected behavior: since www/namnder does not exist, gloo should fall back to www/_default.ext
Actual behavior: Throws 404

**Comment by LudwikJaniuk** [comment]
Will fix this now.
